### ISSUE TITLE
Change display of scout options

### ISSUE THREAD

**Issue by mchiapello** [openvolley/ovscout2#17]
Hello,
is it possible to increase the video loop by decreasing the button size in pop-up interface? I feel the video loop is super useful, but a bit small.

Thank you

**Comment by raymondben** [comment]
Yes, good suggestion, thanks. Will make it an option (which will also be useful in accommodating varying screen sizes).

**Comment by raymondben** [comment]
Make font size (on buttons) variable too, rather than relying on scaling the view in the browser.

**Comment by raymondben** [comment]
Implemented in dev branch, you can now start the scouter with something like
```
ov_scouter(app_styling = list(review_pane_width = 40))
```
(review pane becomes 40% of screen width and the buttons will shrink to accommodate it).

**Comment by mchiapello** [comment]
Hi Ben, 
the new option works very well! Thank you for implemented it.

Just a small side effect: the Botton names remain of the same font size, so some of them are not readable or part of the name is hidden behind the next button. 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/18676022/201273288-109f01c0-7853-4291-b72b-5009a514b3a1.png">

This is very low priority issue.

**Comment by mchiapello** [comment]
Is possible to not have the review panel on top of the court panel? This can be especially useful when you also scout the opponent team and you do not know the player or you cannot see the shirt number. Having the ability to see the court panel can be extremely useful.

This is what I called court panel:
![image](https://user-images.githubusercontent.com/18676022/201314407-91f6d35d-8597-484c-83b8-cee316b915a3.png)

Here for example, I cannot see the number of the receiving player. If the court panel is not hidden by the review panel I can probably infer it.

![image](https://user-images.githubusercontent.com/18676022/201314772-11fb24af-6f3a-4733-9590-2b4aff5f6ad7.png)

**Comment by raymondben** [comment]
If you press 'z' at this point, the popup and review pane will be hidden (while you hold 'z' down) and you can see the court panel

**Comment by raymondben** [comment]
(By the way, if the keyboard shortcuts keys do not suit you, you can change them. The defaults are set by `ov_default_shortcuts()`, so you could:

**Comment by mchiapello** [comment]
I did not know the existence of this keyboard shortcut. Thank you
